name: Deploy AI Automation Project

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Modify this if you want to deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest available version of Ubuntu
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version here

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (optional, you can skip this if you don't have tests)
    - name: Run tests with pytest
      run: |
        pytest  # Adjust this line based on your testi
